# Generated by Django 4.1.6 on 2023-05-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Materials',
        ),
    ]
