# Generated by Django 4.1.6 on 2023-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_rename_person_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='dob',
            field=models.DateField(),
        ),
    ]
