# Generated by Django 4.1.6 on 2023-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_materials_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
